### ISSUE TITLE
Ignored files seem to be to dark in file browser

### ISSUE THREAD

**Issue by aslansky** [aesarius/spacegray-light-ui#1]
Hi, thanks for the really nice theme.

![atom](https://f.cloud.github.com/assets/205002/2383289/ba151002-a8f9-11e3-8209-a118917c3ee3.png)

In the screenshot you can see files and folders that are in .gitignore are getting kind of highlighted because of the darker color. Maybe the other way around would be better.

Cheers,
Alex

**Comment by aesarius** [comment]
Hey mate!
Thanks, glad you like it.
Good catch on the .files :+1: 
Just pushed an update that should fix this issue.
Cheers.

**Comment by aslansky** [comment]
Looks nice now. Thanks.
